testing with trac data
ietf-ribose/tractive pull request #30
Opened 2021-09-07 09:58 UTC by HassanAkbar

Resolves #19 

Test using samples from trac database

2021-09-07 15:03 UTC, ronaldtse requested changes

2021-09-07 15:03 UTC, ronaldtse commented on spec/files/test.config.yaml
> +  '': ''
A mistake?

2021-09-07 15:03 UTC, ronaldtse commented on spec/files/test.config.yaml
> +  henrik: henrik
Do these trac users not have email?

2021-09-08 07:54 UTC, HassanAkbar commented on spec/files/test.config.yaml
> +  '': ''
@ronaldtse This file is created by copying the output of `tractive --info`, and the info is created from the trac database. There are some `empty` values for the owner which are different from NULL values as highlighted in the image below. So that is why there is an entry for the empty value.

<img width="550" alt="Screenshot 2021-09-08 at 12 25 59 PM" src="https://user-images.githubusercontent.com/5301572/132466015-ca817576-000c-47ee-b80e-e64c1e309745.png">

2021-09-08 07:54 UTC, HassanAkbar commented on spec/files/test.config.yaml
> +  henrik: henrik
@ronaldtse This hash is a collection of different columns from different tables:
1. `distinct author from the ticket table`
2. `distinct owner from the ticket table`
3. `distinct author from ticket_change table` etc. 

You can find more detail of these columns here: https://github.com/ietf-ribose/tractive/blob/master/lib/tractive/info.rb#L13
So if there is a name in these columns we will see an entry for name and if there is an email we will see an entry for email. 

In production we will manually have to map these emails/names to valid GitHub usernames otherwise issues will not be created on GitHub.

2021-09-09 00:21 UTC, ronaldtse commented on spec/files/test.config.yaml
> +  henrik: henrik
Got it, please feel free to merge when ready.

2021-09-09 00:22 UTC, ronaldtse commented on spec/files/test.config.yaml
> +  '': ''
Interesting, so there are fields where the "owner" is EMPTY and the "reporter" is NULL...

2021-09-09 00:34 UTC, merged